# Generated by Django 2.2 on 2019-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=60)),
                ('manufacturer', models.CharField(max_length=60)),
                ('car_model', models.CharField(max_length=60)),
                ('car_type', models.CharField(max_length=60)),
                ('engine_type', models.CharField(max_length=60)),
                ('chasis_number', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('tags', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
